### ISSUE TITLE
Trouble deploying backend to heroku

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/group-project#127]
We've been able to successful create an instance of our api on heroku ( "heroku ps:scale web=1" gives a positive result) but we're getting errors in the heroku log and when we view the page in the browser:

Browser Error:
```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

The Heroku Logs spit out a bunch of errors, including this one:
```
 { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

I suspect that this has to do with the .env file, but I still don't really understand what it's for and how to make it work with Heroku. There's also a note in one of the readmes about having to add the client url to .env, but I don't know when to do that or how exactly.

Any guidance would be appreciated!

**Comment by soynog** [comment]
I tried setting the secret key in Heroku using ```heroku config:set SECRET_KEY=[key]``` and now my errors are coming out in teal rather than goldenrod, but they still seem to be mostly the same errors. I'm still getting the ENOENT error at least.

**Comment by laurenfazah** [comment]
`heroku config:set SECRET_KEY=[key]` is the correct approach, just like with deploying our Rails apps. What are the errors now? You said mostly the same, so want to be clear.

**Comment by soynog** [comment]
Here's a sample: 
```
2016-05-18T14:47:21.583408+00:00 heroku[api]: Set SECRET_KEY config vars by nicolas.o.garcia@gmail.com
2016-05-18T14:47:21.583408+00:00 heroku[api]: Release v4 created by nicolas.o.garcia@gmail.com
2016-05-18T14:47:21.809992+00:00 heroku[web.1]: State changed from crashed to starting
2016-05-18T14:47:23.223885+00:00 heroku[web.1]: Starting process with command `npm start`
2016-05-18T14:47:25.538866+00:00 app[web.1]: > express-api-template@0.1.0 start /app
2016-05-18T14:47:25.538846+00:00 app[web.1]: 
2016-05-18T14:47:25.663280+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

**Comment by soynog** [comment]
And in case you're curious, here's what it does next: 

```
2016-05-18T14:47:25.538874+00:00 app[web.1]: > ./bin/express server
2016-05-18T14:47:26.188892+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:242
2016-05-18T14:47:26.188902+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-05-18T14:47:26.204426+00:00 app[web.1]: npm ERR! Linux 3.19.0-59-generic
2016-05-18T14:47:26.204786+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-05-18T14:47:26.188903+00:00 app[web.1]:                                       ^
2016-05-18T14:47:26.188856+00:00 app[web.1]: 
2016-05-18T14:47:26.197640+00:00 app[web.1]: 
2016-05-18T14:47:26.188910+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:916:20)
2016-05-18T14:47:26.204955+00:00 app[web.1]: npm ERR! node v5.11.1
2016-05-18T14:47:26.188909+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2016-05-18T14:47:26.188912+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
2016-05-18T14:47:26.188909+00:00 app[web.1]:     at Object.exports._errnoException (util.js:893:11)
2016-05-18T14:47:26.206523+00:00 app[web.1]: npm ERR! not with npm itself.
2016-05-18T14:47:26.205769+00:00 app[web.1]: npm ERR! express-api-template@0.1.0 start: `./bin/express server`
2016-05-18T14:47:26.207022+00:00 app[web.1]: npm ERR!     npm bugs express-api-template
2016-05-18T14:47:26.205878+00:00 app[web.1]: npm ERR! Exit status 1
2016-05-18T14:47:26.207148+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-05-18T14:47:26.207279+00:00 app[web.1]: npm ERR!     npm owner ls express-api-template
2016-05-18T14:47:26.207383+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-05-18T14:47:26.206004+00:00 app[web.1]: npm ERR! 
2016-05-18T14:47:26.206133+00:00 app[web.1]: npm ERR! Failed at the express-api-template@0.1.0 start script './bin/express server'.
2016-05-18T14:47:26.206270+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-05-18T14:47:26.205368+00:00 app[web.1]: npm ERR! npm  v3.8.6
2016-05-18T14:47:26.206637+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-05-18T14:47:26.206775+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-05-18T14:47:26.206894+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-05-18T14:47:26.205630+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-05-18T14:47:26.206396+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the express-api-template package,
2016-05-18T14:47:26.210730+00:00 app[web.1]: 
2016-05-18T14:47:26.210913+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-05-18T14:47:26.211038+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-05-18T14:47:27.006253+00:00 heroku[web.1]: Process exited with status 1
2016-05-18T14:47:27.017198+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by laurenfazah** [comment]
The `.env` error is just a warning. Configuring the secret key on heroku is all you'd need for that.

The actual error is lying in your second comment. 

`Error: connect ECONNREFUSED 127.0.0.1:27017` is saying your MongoDB connection is erraneous. Have you configured your DB with Mongo? With Rails, we migrated. MongoDB is different. Check out Heroku's docs for this if you're unsure where to start.

**Comment by soynog** [comment]
I went through this tutorial:

https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by laurenfazah** [comment]
Good start for setting up Node. Give this a look for Mongo: https://devcenter.heroku.com/articles/mongolab

**Comment by soynog** [comment]
They're asking us for credit card info to "verify" before we can add MLab. Is this a paid service?

**Comment by laurenfazah** [comment]
Not unless you exceed their free limits - https://mlab.com/plans/pricing/

**Comment by soynog** [comment]
Yeah or you follow the instructions and accidentally sign up for something that they tell you after the fact is $18/month.

FYI for anyone reading this: Don't enter this line.
```
$ heroku addons:create mongolab:shared-cluster-1
```

I've never had someone sign me up for a paid subscription before with no confirmation of the cost. Real annoying.

**Comment by soynog** [comment]
So they've given us a URI to use, and then this line:
> You’ll notice in our driver examples that we use a string (in the standard URI format) to connect. Simply replace this with the connection URI you’ve obtained from the Getting your connection URI section above and you’re good to go. If you need help, feel free to reach out to support@mlab.com.

But there are no driver examples for node.js. The links they give just send us to the install page for mongodb with node. A hint on what to do with the URI would be greatly appreciated.

**Comment by soynog** [comment]
Seem to have gotten it working! As far as I can tell, the critical steps were to set two environment variables:

```heroku config:set SECRET_KEY=[secret key you generated]```
and
```heroku config:set MONGOLAB_URI=[mongoLab uri generated when you setup mongoLab]```

It's possible one of the other various things I did in my flailing was important too, though.

**Comment by soynog** [comment]
Also ```heroku config:set CLIENT_URL=[replace with the first part of your gh-pages url: http://schoof-there-it-is.github.io]```
