### ISSUE TITLE
Problem creating promise chains for UPDATE and GET actions

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/group-project#142]
We are creating promise chains so our users can update and view their profiles.  We're getting parsing error message:

```sh
# edited by @jrhorn424 - please use "preview" to ensure correct format of your issue
/assets/scripts/profile/profile-events.js
Module build failed: SyntaxError: /Users/andreasantarlasci/wdi/projects/bucket-buddy-client/assets/scripts/profile/profile-events.js: Assigning to rvalue (36:2)
 34 | const onShowProfile = () => {
  35 |   // let data = getFormFields(event.target);
> 36 |   new Promise = (resolve, reject) => {
     |   ^
  37 |     api.showProfile(data, (error, response) => {
  38 |       if (error) {
  39 |         reject(error);
    at Parser.pp.raise (/Users/andreasantarlasci/wdi/projects/bucket-buddy-client/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.toAssignable (/Users/andreasantarlasci/wdi/projects/bucket-buddy-client/node_modules/babylon/lib/parser/lval.js:96:14)
```

Here's our code:

```js
// edited by @jrhorn424 - please use "preview" to ensure correct format of your issue
const onShowProfile = () => {
  // let data = getFormFields(event.target);
  new Promise = (resolve, reject) => {
    api.showProfile(data, (error, response) => {
      if (error) {
        reject(error);
      } else {
        resolve(response);
      }
    })
    .then(ui.showProfileSuccess)
    .catch(error)
  };
};

const onUpdateProfile = (event) => {
  // let data = getFormFields(event.target);
  new Promise = (resolve, reject) => {
    api.updateProfile(data, (error, response) => {
      if (error) {
        reject(error);
      } else {
        resolve(response);
      }
    });
  };
};
```

Click handler:

```js
// edited by @jrhorn424 - please use "preview" to ensure correct format of your issue
  $('#update-profile').on('submit', function (event){
      event.preventDefault();
      let data = getFormFields(event.target);
      onUpdateProfile(data)
    //  .then(ui.updateProfileSuccess)
      .then(onShowProfile)
      .catch(error)
  });
```

**Comment by jrhorn424** [comment]
Please use "preview" to ensure correct format of your issue.

**Comment by jrhorn424** [comment]
```
> 36 |   new Promise = (resolve, reject) => {
```

That's not how you call a constructor.

**Comment by andreasantarl** [comment]
The constructor was fixed.

We aren't making it to our second promise in the promise chain.  WUTTTTT????

**Comment by jrhorn424** [comment]
Promises were being defined in the wrong place.

```
const onUpdateProfile = (event) => {
  // let data = getFormFields(event.target);
  new Promise = (resolve, reject) => {
    api.updateProfile(data, (error, response) => {
      if (error) {
        reject(error);
      } else {
        resolve(response);
      }
    });
  };
};
```

The `api.updateProfile` function **call** is not asynchronous, but it contains asynchronous code. Additionally, the signature for `api.updateProfile` did not accept a callback. The callback passed was copied from a node promise lesson, since node API functions have an error-first, one parameter signature.

Instead of defining the Promise and returning it from `onUpdateProfile`, the Promise should be defined and returned from `api.updateProfile`.
