### ISSUE TITLE
Heroko Deployment Errors

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/group-project#147]
Followed the steps in Shireen's issue to deploy, but still hitting errors. Heroku log reads: 

```
2016-07-14T18:27:24.187706+00:00 app[web.1]: npm ERR! Failed at the bucket-buddy-api@0.1.0 start script './bin/express server'.
2016-07-14T18:27:24.187918+00:00 app[web.1]: npm ERR! This is most likely a problem with the bucket-buddy-api package,
2016-07-14T18:27:24.188123+00:00 app[web.1]: npm ERR! not with npm itself.
2016-07-14T18:27:24.204798+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-07-14T18:27:24.103879+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-07-14T18:27:24.204994+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-07-14T18:27:24.205928+00:00 app[web.1]: npm ERR!     npm owner ls bucket-buddy-api
2016-07-14T18:27:24.206116+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-07-14T18:27:24.211989+00:00 app[web.1]: 
2016-07-14T18:27:24.220407+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-07-14T18:27:24.220593+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-07-14T18:27:24.205230+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-07-14T18:27:24.205395+00:00 app[web.1]: npm ERR!     npm bugs bucket-buddy-api
2016-07-14T18:27:24.205566+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-07-14T18:27:24.205746+00:00 app[web.1]: npm ERR! 
2016-07-14T18:27:25.439596+00:00 heroku[web.1]: Process exited with status 1
2016-07-14T18:27:25.454802+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-14T18:27:29.492177+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=bucket-buddy-api.herokuapp.com request_id=3fbe799f-9cd2-44b3-a677-4080eb7e372e fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-07-14T18:27:29.717555+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=bucket-buddy-api.herokuapp.com request_id=fc92e8d2-89ea-4f16-b5c5-9079c00195c3 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-07-14T18:29:10.366044+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=bucket-buddy-api.herokuapp.com request_id=f99d24b2-b8dc-442f-bd15-034c0cef88f3 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-07-14T18:32:34.455110+00:00 heroku[slug-compiler]: Slug compilation started
2016-07-14T18:32:34.455119+00:00 heroku[slug-compiler]: Slug compilation finished
2016-07-14T18:32:34.798413+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-14T18:32:36.133890+00:00 heroku[web.1]: Starting process with command `npm start`
2016-07-14T18:32:38.009114+00:00 app[web.1]: > bucket-buddy-api@0.1.0 start /app
2016-07-14T18:32:38.009090+00:00 app[web.1]: 
2016-07-14T18:32:38.009120+00:00 app[web.1]: > ./bin/express server
2016-07-14T18:32:38.009121+00:00 app[web.1]: 
2016-07-14T18:32:39.191109+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:231
2016-07-14T18:32:39.191110+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-07-14T18:32:38.998477+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2016-07-14T18:32:39.191093+00:00 app[web.1]: 
2016-07-14T18:32:39.191111+00:00 app[web.1]:                                       ^
2016-07-14T18:32:39.207993+00:00 app[web.1]: npm ERR! npm  v2.14.20
2016-07-14T18:32:39.207499+00:00 app[web.1]: npm ERR! node v4.4.0
2016-07-14T18:32:39.191116+00:00 app[web.1]:     at errnoException (dns.js:26:10)
2016-07-14T18:32:39.207023+00:00 app[web.1]: npm ERR! Linux 3.13.0-85-generic
2016-07-14T18:32:39.200821+00:00 app[web.1]: 
2016-07-14T18:32:39.207328+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-07-14T18:32:39.191117+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
2016-07-14T18:32:39.208714+00:00 app[web.1]: npm ERR! bucket-buddy-api@0.1.0 start: `./bin/express server`
2016-07-14T18:32:39.191115+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND undefined undefined:27017
2016-07-14T18:32:39.208585+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-07-14T18:32:39.209572+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-07-14T18:32:39.209152+00:00 app[web.1]: npm ERR! Failed at the bucket-buddy-api@0.1.0 start script './bin/express server'.
2016-07-14T18:32:39.208902+00:00 app[web.1]: npm ERR! Exit status 1
2016-07-14T18:32:39.209033+00:00 app[web.1]: npm ERR! 
2016-07-14T18:32:39.209267+00:00 app[web.1]: npm ERR! This is most likely a problem with the bucket-buddy-api package,
2016-07-14T18:32:39.209365+00:00 app[web.1]: npm ERR! not with npm itself.
2016-07-14T18:32:39.209667+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-07-14T18:32:39.209777+00:00 app[web.1]: npm ERR!     npm bugs bucket-buddy-api
2016-07-14T18:32:39.209873+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-07-14T18:32:39.209967+00:00 app[web.1]: npm ERR! 
2016-07-14T18:32:39.210062+00:00 app[web.1]: npm ERR!     npm owner ls bucket-buddy-api
2016-07-14T18:32:39.210208+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-07-14T18:32:39.213819+00:00 app[web.1]: 
2016-07-14T18:32:39.214039+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-07-14T18:32:39.214203+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-07-14T18:32:39.209460+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-07-14T18:32:39.966627+00:00 heroku[web.1]: Process exited with status 1
2016-07-14T18:32:39.981262+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-14T18:34:15.225069+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-14T18:34:16.899785+00:00 heroku[web.1]: Starting process with command `npm start`
2016-07-14T18:34:19.409649+00:00 app[web.1]: 
2016-07-14T18:34:19.409687+00:00 app[web.1]: > ./bin/express server
2016-07-14T18:34:19.409688+00:00 app[web.1]: 
2016-07-14T18:34:19.409676+00:00 app[web.1]: > bucket-buddy-api@0.1.0 start /app
2016-07-14T18:34:20.290192+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2016-07-14T18:34:20.561926+00:00 app[web.1]: 
2016-07-14T18:34:20.561975+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-07-14T18:34:20.592303+00:00 app[web.1]: npm ERR! node v4.4.0
2016-07-14T18:34:20.561973+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:231
2016-07-14T18:34:20.561976+00:00 app[web.1]:                                       ^
2016-07-14T18:34:20.592120+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-07-14T18:34:20.592740+00:00 app[web.1]: npm ERR! npm  v2.14.20
2016-07-14T18:34:20.593085+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-07-14T18:34:20.561983+00:00 app[web.1]:     at errnoException (dns.js:26:10)
2016-07-14T18:34:20.561983+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
2016-07-14T18:34:20.591825+00:00 app[web.1]: npm ERR! Linux 3.13.0-85-generic
2016-07-14T18:34:20.561982+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND undefined undefined:27017
2016-07-14T18:34:20.580975+00:00 app[web.1]: 
2016-07-14T18:34:20.593226+00:00 app[web.1]: npm ERR! bucket-buddy-api@0.1.0 start: `./bin/express server`
2016-07-14T18:34:20.594009+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-07-14T18:34:20.594140+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-07-14T18:34:20.593334+00:00 app[web.1]: npm ERR! Exit status 1
2016-07-14T18:34:20.594293+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-07-14T18:34:20.593464+00:00 app[web.1]: npm ERR! 
2016-07-14T18:34:20.593617+00:00 app[web.1]: npm ERR! Failed at the bucket-buddy-api@0.1.0 start script './bin/express server'.
2016-07-14T18:34:20.593744+00:00 app[web.1]: npm ERR! This is most likely a problem with the bucket-buddy-api package,
2016-07-14T18:34:20.593873+00:00 app[web.1]: npm ERR! not with npm itself.
2016-07-14T18:34:20.594420+00:00 app[web.1]: npm ERR!     npm bugs bucket-buddy-api
2016-07-14T18:34:20.601492+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-07-14T18:34:20.595067+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-07-14T18:34:20.601022+00:00 app[web.1]: 
2016-07-14T18:34:20.601364+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-07-14T18:34:20.594710+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-07-14T18:34:20.594853+00:00 app[web.1]: npm ERR! 
2016-07-14T18:34:20.594965+00:00 app[web.1]: npm ERR!     npm owner ls bucket-buddy-api
2016-07-14T18:34:21.563819+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-14T18:34:14.971599+00:00 heroku[api]: Set SECRET_KEY config vars by lcurran327@gmail.com
2016-07-14T18:34:14.971599+00:00 heroku[api]: Release v10 created by lcurran327@gmail.com
```

**Comment by J-Weeks** [comment]
Can you link the issue you're referencing?

**Comment by lcurran** [comment]
https://github.com/ga-wdi-boston/group-project/issues/141

**Comment by J-Weeks** [comment]
Talking to Lauren she referenced this issue https://github.com/ga-wdi-boston/group-project/issues/127

**Comment by lcurran** [comment]
MONGODB_URI set, NODE_ENV set and SECRET_KEY set: new error
```sh
2016-07-14T20:31:36.268427+00:00 app[web.1]: npm ERR!     npm owner ls bucket-buddy-api
2016-07-14T20:31:36.266941+00:00 app[web.1]: npm ERR! Exit status 1
2016-07-14T20:31:36.268627+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-07-14T20:31:36.273815+00:00 app[web.1]: 
2016-07-14T20:31:36.274114+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-07-14T20:31:36.267492+00:00 app[web.1]: npm ERR! not with npm itself.
2016-07-14T20:31:36.267596+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-07-14T20:31:36.274309+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-07-14T20:31:36.268230+00:00 app[web.1]: npm ERR! 
2016-07-14T20:31:36.989933+00:00 heroku[web.1]: Process exited with status 1
2016-07-14T20:31:37.011726+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-14T20:31:30.851819+00:00 heroku[api]: Release v4 created by lcurran327@gmail.com
2016-07-14T20:31:30.851729+00:00 heroku[api]: Set NODE_ENV config vars by lcurran327@gmail.com
2016-07-14T20:32:01.911841+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-14T20:32:03.265038+00:00 heroku[web.1]: Starting process with command `npm start`
2016-07-14T20:32:06.027344+00:00 app[web.1]: 
2016-07-14T20:32:06.027378+00:00 app[web.1]: > bucket-buddy-api@0.1.0 start /app
2016-07-14T20:32:06.027384+00:00 app[web.1]: > ./bin/express server
2016-07-14T20:32:06.027385+00:00 app[web.1]: 
2016-07-14T20:32:06.915820+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND undefined undefined:27017
2016-07-14T20:32:06.915820+00:00 app[web.1]:     at errnoException (dns.js:26:10)
2016-07-14T20:32:06.915812+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:231
2016-07-14T20:32:06.915815+00:00 app[web.1]:                                       ^
2016-07-14T20:32:06.915787+00:00 app[web.1]: 
2016-07-14T20:32:06.915814+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-07-14T20:32:06.698623+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2016-07-14T20:32:06.943274+00:00 app[web.1]: npm ERR! Exit status 1
2016-07-14T20:32:06.943449+00:00 app[web.1]: npm ERR! 
2016-07-14T20:32:06.942926+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-07-14T20:32:06.943642+00:00 app[web.1]: npm ERR! Failed at the bucket-buddy-api@0.1.0 start script './bin/express server'.
2016-07-14T20:32:06.943833+00:00 app[web.1]: npm ERR! This is most likely a problem with the bucket-buddy-api package,
2016-07-14T20:32:06.943995+00:00 app[web.1]: npm ERR! not with npm itself.
2016-07-14T20:32:06.944199+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-07-14T20:32:06.943103+00:00 app[web.1]: npm ERR! bucket-buddy-api@0.1.0 start: `./bin/express server`
2016-07-14T20:32:06.915821+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
2016-07-14T20:32:06.931870+00:00 app[web.1]: 
2016-07-14T20:32:06.941217+00:00 app[web.1]: npm ERR! Linux 3.13.0-85-generic
2016-07-14T20:32:06.941714+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-07-14T20:32:06.942042+00:00 app[web.1]: npm ERR! node v4.4.0
2016-07-14T20:32:06.942703+00:00 app[web.1]: npm ERR! npm  v2.14.20
2016-07-14T20:32:06.945244+00:00 app[web.1]: npm ERR!     npm owner ls bucket-buddy-api
2016-07-14T20:32:06.948935+00:00 app[web.1]: 
2016-07-14T20:32:06.949179+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-07-14T20:32:06.944408+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-07-14T20:32:06.944569+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-07-14T20:32:06.944735+00:00 app[web.1]: npm ERR!     npm bugs bucket-buddy-api
2016-07-14T20:32:06.944920+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-07-14T20:32:06.945082+00:00 app[web.1]: npm ERR! 
2016-07-14T20:32:06.945399+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-07-14T20:32:06.949355+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-07-14T20:32:07.685379+00:00 heroku[web.1]: Process exited with status 1
2016-07-14T20:32:07.698703+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-14T20:32:01.544351+00:00 heroku[api]: Release v5 created by lcurran327@gmail.com
2016-07-14T20:32:01.544351+00:00 heroku[api]: Attach MONGODB (@ref:mongolab-sinuous-74464) by lcurran327@gmail.com
2016-07-14T20:33:20.957443+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-14T20:33:23.024476+00:00 heroku[web.1]: Starting process with command `npm start`
2016-07-14T20:33:26.615774+00:00 app[web.1]: > bucket-buddy-api@0.1.0 start /app
2016-07-14T20:33:26.615761+00:00 app[web.1]: 
2016-07-14T20:33:26.615775+00:00 app[web.1]: > ./bin/express server
2016-07-14T20:33:26.615776+00:00 app[web.1]: 
2016-07-14T20:33:28.570843+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2016-07-14T20:33:28.938482+00:00 app[web.1]:     at errnoException (dns.js:26:10)
2016-07-14T20:33:28.938482+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
2016-07-14T20:33:28.938473+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mongodb/lib/server.js:231
2016-07-14T20:33:28.961279+00:00 app[web.1]: npm ERR! Linux 3.13.0-91-generic
2016-07-14T20:33:28.938481+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND undefined undefined:27017
2016-07-14T20:33:28.938457+00:00 app[web.1]: 
2016-07-14T20:33:28.952743+00:00 app[web.1]: 
2016-07-14T20:33:28.938475+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-07-14T20:33:28.938476+00:00 app[web.1]:                                       ^
2016-07-14T20:33:28.961755+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-07-14T20:33:28.962017+00:00 app[web.1]: npm ERR! node v4.4.0
2016-07-14T20:33:28.962811+00:00 app[web.1]: npm ERR! npm  v2.14.20
2016-07-14T20:33:28.963068+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-07-14T20:33:28.965796+00:00 app[web.1]: npm ERR! 
2016-07-14T20:33:28.965798+00:00 app[web.1]: npm ERR! Failed at the bucket-buddy-api@0.1.0 start script './bin/express server'.
2016-07-14T20:33:28.965802+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-07-14T20:33:28.965802+00:00 app[web.1]: npm ERR!     npm bugs bucket-buddy-api
2016-07-14T20:33:28.965798+00:00 app[web.1]: npm ERR! This is most likely a problem with the bucket-buddy-api package,
2016-07-14T20:33:28.965803+00:00 app[web.1]: npm ERR! 
2016-07-14T20:33:28.965803+00:00 app[web.1]: npm ERR!     npm owner ls bucket-buddy-api
2016-07-14T20:33:28.965804+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-07-14T20:33:28.986634+00:00 app[web.1]: 
2016-07-14T20:33:28.986947+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-07-14T20:33:28.965799+00:00 app[web.1]: npm ERR! not with npm itself.
2016-07-14T20:33:28.965800+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-07-14T20:33:28.963250+00:00 app[web.1]: npm ERR! bucket-buddy-api@0.1.0 start: `./bin/express server`
2016-07-14T20:33:28.963424+00:00 app[web.1]: npm ERR! Exit status 1
2016-07-14T20:33:28.987103+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-07-14T20:33:28.965800+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-07-14T20:33:28.965801+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-07-14T20:33:30.097408+00:00 heroku[web.1]: Process exited with status 1
2016-07-14T20:33:30.115653+00:00 heroku[web.1]: State changed from starting to crashed
2016-07-14T20:48:51.476914+00:00 heroku[web.1]: State changed from crashed to starting
2016-07-14T20:48:53.395171+00:00 heroku[web.1]: Starting process with command `npm start`
2016-07-14T20:48:55.865224+00:00 heroku[web.1]: Restarting
2016-07-14T20:48:57.245786+00:00 heroku[web.1]: Starting process with command `npm start`
2016-07-14T20:48:57.317592+00:00 app[web.1]: > bucket-buddy-api@0.1.0 start /app
2016-07-14T20:48:57.317594+00:00 app[web.1]: 
2016-07-14T20:48:57.317593+00:00 app[web.1]: > ./bin/express server
2016-07-14T20:48:57.317573+00:00 app[web.1]: 
```

**Comment by jrhorn424** [comment]
Some of those are old errors, and I'm not certain it contains all the most recent errors. Sometimes after an error it takes a few seconds to show up in the logs. Please paste only recent errors in a new comment so we can help diagnose. To do so, run `heroku logs`, find the most recent action you took (for example, maybe it was attaching Mongo? in any case, it should start with `heroku[api]`), then only paste errors after that event.

If you're having trouble isolating, see if you can try `heroku restart`. If it's been a while since any activity on the server, the most recent timestamps should be the ones you want after the failed restart.

**Comment by jrhorn424** [comment]
Moreover,

> MONGODB_URI set, NODE_ENV set and SECRET_KEY set: new error

I'm not sure it's a new error. The most recent error I see is the same as one of the first:

> Error: getaddrinfo ENOTFOUND undefined undefined:27017

That port is the key. What port is it? What should come before a port? Definitely not `undefined`. What does that sound like? Maybe a bad assignment... maybe a bad URL in heroku... maybe a typo...

**Comment by lcurran** [comment]
Solved.

Problem is the Express template has `process.env.MONGOLAB_URI`, and my problem was I copied Jeff's response from Shireen's issue which also has `uri = process.env.MONGOLAB_URI`.

To fix:

the app/middleware/mongoose.js file needs to have:

```
const uri = process.env.MONGODB_URI || 'mongodb://localhost/your-api';
```

and you need to run:
```
heroku config:get MONGODB_URI

```

**Comment by jrhorn424** [comment]
I edited Shireen's last update on that issue. I take no offense, I should have edited my response as well. But the answer was there, as the last comment in the thread. :wink:

**Comment by jrhorn424** [comment]
After checking in with Brian, I see now that the template also has a different variable name.

The variable name doesn't matter, but it whatever you choose for the variable name on heroku should also be the variable name in your mongoose configuration file.
