### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/group-project#158]
We got application error. Not sure where we should start debugging. 

```
~/wdi/projects/ecommerce-back (master)$ heroku logs
2016-09-07T16:55:00.395791+00:00 app[web.1]: > express-api-template@0.1.0 start /app
2016-09-07T16:55:00.395791+00:00 app[web.1]: > ./bin/express server
2016-09-07T16:55:00.395792+00:00 app[web.1]: 
2016-09-07T16:55:00.844743+00:00 heroku[web.1]: Starting process with command `npm start`
2016-09-07T16:55:02.237161+00:00 app[web.1]: module.js:327
2016-09-07T16:55:02.237242+00:00 app[web.1]:     throw err;
2016-09-07T16:55:02.237254+00:00 app[web.1]:     ^
2016-09-07T16:55:02.237265+00:00 app[web.1]: 
2016-09-07T16:55:02.237278+00:00 app[web.1]: Error: Cannot find module 'stripe'
2016-09-07T16:55:02.237280+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:325:15)
2016-09-07T16:55:02.237281+00:00 app[web.1]:     at Function.Module._load (module.js:276:25)
2016-09-07T16:55:02.237281+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T16:55:02.237283+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/orders.js:9:16)
2016-09-07T16:55:02.237282+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T16:55:02.237283+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T16:55:02.237284+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-09-07T16:55:02.237284+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-09-07T16:55:02.237285+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-09-07T16:55:02.237286+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T16:55:02.237286+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T16:55:02.237287+00:00 app[web.1]:     at /app/lib/wiring/loader.js:13:39
2016-09-07T16:55:02.237288+00:00 app[web.1]:     at Array.forEach (native)
2016-09-07T16:55:02.237288+00:00 app[web.1]:     at fs.readdirSync.filter.entry.forEach (/app/lib/wiring/loader.js:12:5)
2016-09-07T16:55:02.237289+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/index.js:5:18)
2016-09-07T16:55:02.237300+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T16:55:02.355763+00:00 app[web.1]: 
2016-09-07T16:55:02.367112+00:00 app[web.1]: npm ERR! Linux 3.13.0-85-generic
2016-09-07T16:55:02.367586+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-09-07T16:55:02.368228+00:00 app[web.1]: npm ERR! node v4.5.0
2016-09-07T16:55:02.368328+00:00 app[web.1]: npm ERR! npm  v2.15.9
2016-09-07T16:55:02.368580+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-09-07T16:55:02.368809+00:00 app[web.1]: npm ERR! express-api-template@0.1.0 start: `./bin/express server`
2016-09-07T16:55:02.368996+00:00 app[web.1]: npm ERR! Exit status 1
2016-09-07T16:55:02.369326+00:00 app[web.1]: npm ERR! 
2016-09-07T16:55:02.369509+00:00 app[web.1]: npm ERR! Failed at the express-api-template@0.1.0 start script './bin/express server'.
2016-09-07T16:55:02.369726+00:00 app[web.1]: npm ERR! This is most likely a problem with the express-api-template package,
2016-09-07T16:55:02.369939+00:00 app[web.1]: npm ERR! not with npm itself.
2016-09-07T16:55:02.370131+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-09-07T16:55:02.370386+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-09-07T16:55:02.370587+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-09-07T16:55:02.371242+00:00 app[web.1]: npm ERR!     npm bugs express-api-template
2016-09-07T16:55:02.371427+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-09-07T16:55:02.371635+00:00 app[web.1]: npm ERR! 
2016-09-07T16:55:02.371810+00:00 app[web.1]: npm ERR!     npm owner ls express-api-template
2016-09-07T16:55:02.371977+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-09-07T16:55:02.377764+00:00 app[web.1]: 
2016-09-07T16:55:02.378059+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-09-07T16:55:02.378219+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-09-07T16:55:02.496067+00:00 heroku[web.1]: Process exited with status 1
2016-09-07T16:55:03.398829+00:00 app[web.1]: 
2016-09-07T16:55:03.398843+00:00 app[web.1]: > ./bin/express server
2016-09-07T16:55:03.398843+00:00 app[web.1]: > express-api-template@0.1.0 start /app
2016-09-07T16:55:03.398844+00:00 app[web.1]: 
2016-09-07T16:55:04.508266+00:00 app[web.1]:     ^
2016-09-07T16:55:04.508274+00:00 app[web.1]: 
2016-09-07T16:55:04.508288+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T16:55:04.508287+00:00 app[web.1]:     at Function.Module._load (module.js:276:25)
2016-09-07T16:55:04.508285+00:00 app[web.1]: Error: Cannot find module 'stripe'
2016-09-07T16:55:04.508287+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:325:15)
2016-09-07T16:55:04.508290+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T16:55:04.508257+00:00 app[web.1]:     throw err;
2016-09-07T16:55:04.508291+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-09-07T16:55:04.508291+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-09-07T16:55:04.508289+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T16:55:04.508292+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-09-07T16:55:04.508292+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T16:55:04.508293+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T16:55:04.508293+00:00 app[web.1]:     at /app/lib/wiring/loader.js:13:39
2016-09-07T16:55:04.508295+00:00 app[web.1]:     at fs.readdirSync.filter.entry.forEach (/app/lib/wiring/loader.js:12:5)
2016-09-07T16:55:04.508185+00:00 app[web.1]: module.js:327
2016-09-07T16:55:04.508294+00:00 app[web.1]:     at Array.forEach (native)
2016-09-07T16:55:04.508296+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/index.js:5:18)
2016-09-07T16:55:04.524117+00:00 app[web.1]: 
2016-09-07T16:55:04.534376+00:00 app[web.1]: npm ERR! Linux 3.13.0-93-generic
2016-09-07T16:55:04.508289+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/orders.js:9:16)
2016-09-07T16:55:04.534778+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-09-07T16:55:04.535053+00:00 app[web.1]: npm ERR! node v4.5.0
2016-09-07T16:55:04.536012+00:00 app[web.1]: npm ERR! express-api-template@0.1.0 start: `./bin/express server`
2016-09-07T16:55:04.535605+00:00 app[web.1]: npm ERR! npm  v2.15.9
2016-09-07T16:55:04.508304+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T16:55:04.535829+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-09-07T16:55:04.536181+00:00 app[web.1]: npm ERR! Exit status 1
2016-09-07T16:55:04.536367+00:00 app[web.1]: npm ERR! 
2016-09-07T16:55:04.537097+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-09-07T16:55:04.536761+00:00 app[web.1]: npm ERR! This is most likely a problem with the express-api-template package,
2016-09-07T16:55:04.536922+00:00 app[web.1]: npm ERR! not with npm itself.
2016-09-07T16:55:04.537285+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-09-07T16:55:04.537559+00:00 app[web.1]: npm ERR!     npm bugs express-api-template
2016-09-07T16:55:04.537677+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-09-07T16:55:04.536551+00:00 app[web.1]: npm ERR! Failed at the express-api-template@0.1.0 start script './bin/express server'.
2016-09-07T16:55:04.537791+00:00 app[web.1]: npm ERR! 
2016-09-07T16:55:04.538012+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-09-07T16:55:04.541632+00:00 app[web.1]: 
2016-09-07T16:55:04.542097+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-09-07T16:55:04.541919+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-09-07T16:55:04.537433+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-09-07T16:55:04.537892+00:00 app[web.1]: npm ERR!     npm owner ls express-api-template
2016-09-07T16:55:04.662464+00:00 heroku[web.1]: Process exited with status 1
2016-09-07T16:55:04.675286+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-07T16:55:05.443917+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fathomless-everglades-52108.herokuapp.com request_id=8f630915-9645-4376-b3b9-c4c20ed0f460 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-09-07T16:55:05.868974+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=fathomless-everglades-52108.herokuapp.com request_id=b0b145be-0e35-4977-aba1-836d413c803c fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
~/wdi/projects/ecommerce-back (master)$ 
```

**Comment by NatasaPeic** [comment]
We set MONGOLAB_URI as Jordan explained in his issue.

**Comment by gaand** [comment]
`Error: Cannot find module 'stripe'`

**Comment by NatasaPeic** [comment]
I just ran npm install --save stripe. 

```
~/wdi/projects/ecommerce-back (master)$ heroku logs
2016-09-07T17:03:01.046647+00:00 app[web.1]:     throw err;
2016-09-07T17:03:01.046660+00:00 app[web.1]:     ^
2016-09-07T17:03:01.046670+00:00 app[web.1]: 
2016-09-07T17:03:01.046682+00:00 app[web.1]: Error: Cannot find module 'stripe'
2016-09-07T17:03:01.046683+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:325:15)
2016-09-07T17:03:01.046684+00:00 app[web.1]:     at Function.Module._load (module.js:276:25)
2016-09-07T17:03:01.046684+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T17:03:01.046685+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T17:03:01.046686+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/orders.js:9:16)
2016-09-07T17:03:01.046686+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T17:03:01.046687+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-09-07T17:03:01.046688+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-09-07T17:03:01.046688+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-09-07T17:03:01.046690+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T17:03:01.046689+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T17:03:01.046690+00:00 app[web.1]:     at /app/lib/wiring/loader.js:13:39
2016-09-07T17:03:01.046691+00:00 app[web.1]:     at Array.forEach (native)
2016-09-07T17:03:01.046692+00:00 app[web.1]:     at fs.readdirSync.filter.entry.forEach (/app/lib/wiring/loader.js:12:5)
2016-09-07T17:03:01.046693+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/index.js:5:18)
2016-09-07T17:03:01.046704+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T17:03:01.074438+00:00 app[web.1]: 
2016-09-07T17:03:01.085647+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-09-07T17:03:01.085166+00:00 app[web.1]: npm ERR! Linux 3.13.0-93-generic
2016-09-07T17:03:01.085948+00:00 app[web.1]: npm ERR! node v4.5.0
2016-09-07T17:03:01.086864+00:00 app[web.1]: npm ERR! npm  v2.15.9
2016-09-07T17:03:01.087135+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-09-07T17:03:01.087361+00:00 app[web.1]: npm ERR! express-api-template@0.1.0 start: `./bin/express server`
2016-09-07T17:03:01.087565+00:00 app[web.1]: npm ERR! Exit status 1
2016-09-07T17:03:01.087784+00:00 app[web.1]: npm ERR! 
2016-09-07T17:03:01.088002+00:00 app[web.1]: npm ERR! Failed at the express-api-template@0.1.0 start script './bin/express server'.
2016-09-07T17:03:01.088226+00:00 app[web.1]: npm ERR! This is most likely a problem with the express-api-template package,
2016-09-07T17:03:01.088424+00:00 app[web.1]: npm ERR! not with npm itself.
2016-09-07T17:03:01.089063+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-09-07T17:03:01.089274+00:00 app[web.1]: npm ERR!     npm bugs express-api-template
2016-09-07T17:03:01.088639+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-09-07T17:03:01.088844+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-09-07T17:03:01.089492+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-09-07T17:03:01.089721+00:00 app[web.1]: npm ERR! 
2016-09-07T17:03:01.090154+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-09-07T17:03:01.089938+00:00 app[web.1]: npm ERR!     npm owner ls express-api-template
2016-09-07T17:03:01.095111+00:00 app[web.1]: 
2016-09-07T17:03:01.095577+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-09-07T17:03:01.095421+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-09-07T17:03:01.236246+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-07T17:03:01.222777+00:00 heroku[web.1]: Process exited with status 1
2016-09-07T17:03:02.505868+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fathomless-everglades-52108.herokuapp.com request_id=b0ad9e61-0793-4ed3-8ff9-833e44844421 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-09-07T17:03:02.904710+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=fathomless-everglades-52108.herokuapp.com request_id=9286eec3-d90c-46f5-9625-dddb7b7d7dc6 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-09-07T17:06:01.662686+00:00 heroku[web.1]: State changed from crashed to starting
2016-09-07T17:06:03.698907+00:00 heroku[web.1]: Starting process with command `npm start`
2016-09-07T17:06:06.694678+00:00 app[web.1]: 
2016-09-07T17:06:06.694693+00:00 app[web.1]: > express-api-template@0.1.0 start /app
2016-09-07T17:06:06.694693+00:00 app[web.1]: > ./bin/express server
2016-09-07T17:06:06.694694+00:00 app[web.1]: 
2016-09-07T17:06:07.888416+00:00 app[web.1]: module.js:327
2016-09-07T17:06:07.888424+00:00 app[web.1]:     throw err;
2016-09-07T17:06:07.888425+00:00 app[web.1]:     ^
2016-09-07T17:06:07.888426+00:00 app[web.1]: 
2016-09-07T17:06:07.888427+00:00 app[web.1]: Error: Cannot find module 'stripe'
2016-09-07T17:06:07.888430+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:325:15)
2016-09-07T17:06:07.888431+00:00 app[web.1]:     at Function.Module._load (module.js:276:25)
2016-09-07T17:06:07.888432+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T17:06:07.888432+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T17:06:07.888433+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/orders.js:9:16)
2016-09-07T17:06:07.888434+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T17:06:07.888434+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-09-07T17:06:07.888435+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-09-07T17:06:07.888436+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-09-07T17:06:07.888436+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-09-07T17:06:07.888437+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-09-07T17:06:07.888438+00:00 app[web.1]:     at /app/lib/wiring/loader.js:13:39
2016-09-07T17:06:07.888438+00:00 app[web.1]:     at Array.forEach (native)
2016-09-07T17:06:07.888440+00:00 app[web.1]:     at fs.readdirSync.filter.entry.forEach (/app/lib/wiring/loader.js:12:5)
2016-09-07T17:06:07.888440+00:00 app[web.1]:     at Object.<anonymous> (/app/app/controllers/index.js:5:18)
2016-09-07T17:06:07.888444+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-09-07T17:06:07.901874+00:00 app[web.1]: 
2016-09-07T17:06:07.910472+00:00 app[web.1]: npm ERR! Linux 3.13.0-91-generic
2016-09-07T17:06:07.910922+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-09-07T17:06:07.911176+00:00 app[web.1]: npm ERR! node v4.5.0
2016-09-07T17:06:07.912004+00:00 app[web.1]: npm ERR! npm  v2.15.9
2016-09-07T17:06:07.912248+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-09-07T17:06:07.912454+00:00 app[web.1]: npm ERR! express-api-template@0.1.0 start: `./bin/express server`
2016-09-07T17:06:07.912628+00:00 app[web.1]: npm ERR! Exit status 1
2016-09-07T17:06:07.912847+00:00 app[web.1]: npm ERR! 
2016-09-07T17:06:07.913035+00:00 app[web.1]: npm ERR! Failed at the express-api-template@0.1.0 start script './bin/express server'.
2016-09-07T17:06:07.913220+00:00 app[web.1]: npm ERR! This is most likely a problem with the express-api-template package,
2016-09-07T17:06:07.913395+00:00 app[web.1]: npm ERR! not with npm itself.
2016-09-07T17:06:07.913571+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-09-07T17:06:07.913738+00:00 app[web.1]: npm ERR!     ./bin/express server
2016-09-07T17:06:07.913947+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-09-07T17:06:07.914144+00:00 app[web.1]: npm ERR!     npm bugs express-api-template
2016-09-07T17:06:07.914343+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-09-07T17:06:07.914557+00:00 app[web.1]: npm ERR! 
2016-09-07T17:06:07.914732+00:00 app[web.1]: npm ERR!     npm owner ls express-api-template
2016-09-07T17:06:07.914913+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-09-07T17:06:07.919164+00:00 app[web.1]: 
2016-09-07T17:06:07.919431+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-09-07T17:06:07.919590+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-09-07T17:06:08.068212+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-07T17:06:08.052986+00:00 heroku[web.1]: Process exited with status 1
2016-09-07T17:06:09.304397+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fathomless-everglades-52108.herokuapp.com request_id=2750db8a-d5d2-49b3-9894-ba1dabe940d9 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
2016-09-07T17:06:09.702685+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=fathomless-everglades-52108.herokuapp.com request_id=c387737f-ec9a-41ac-83c2-7287f9e858e6 fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
```

Still errors.

**Comment by NatasaPeic** [comment]
Ok. Add and commit. Push origin heroku master did the trick.

It is deployed.

Thank  you.
