### ISSUE TITLE
.DS_store crashing nodemon

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/group-project#188]
I need some help with a very odd nodemon error
```[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./bin/express server`
/Users/treep78/wdi/projects/project3/e-com-back-end/app/controllers/.DS_Store:1
(function (exports, require, module, __filename, __dirname) { 
                                                              

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/treep78/wdi/projects/project3/e-com-back-end/lib/wiring/loader.js:13:39
    at Array.forEach (native)
    at fs.readdirSync.filter.entry.forEach (/Users/treep78/wdi/projects/project3/e-com-back-end/lib/wiring/loader.js:12:5)
    at Object.<anonymous> (/Users/treep78/wdi/projects/project3/e-com-back-end/app/controllers/index.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[nodemon] app crashed - waiting for file changes before starting…
```

I couldn’t find anything online about it. It started cropping up after I move files in an out of a folder.

**Comment by treep78** [comment]
deleting .DS_store seems to fix the issue at least temporarily

**Comment by treep78** [comment]
I'll reopen this if the bug comes back

**Comment by raq929** [comment]
When you see this `SyntaxError: Unexpected token ILLEGAL` it means there's a syntax error in your code. Check your linter and fix the error, and nodemon will restart.
