### ISSUE TITLE
Unable to properly setup an embedded document relationship

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/group-project#196]
I am trying to create an array of embedded documents. We are doing the e-commerce prompt and currently our program is setup as such.

I am using this documentation to try to figure this out: [http://mongoosejs.com/docs/2.7.x/docs/embedded-documents.html](http://mongoosejs.com/docs/2.7.x/docs/embedded-documents.html)

`User` model has a `cart` key which is an array to hold `CartProduct` models. 

The User model looks like: 

```js
'use strict';

const bcrypt = require('bcrypt');
const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator');
const CartProduct = require('./cartproduct');

const userSchema = new mongoose.Schema({
  email: {
    type: String,
    unique: true,
    required: true,
  },
  cart: {
    type: [CartProduct], //Here we define that cart is an array of CartProduct
    default: [],
  },
  token: {
    type: String,
    require: true,
  },
  passwordDigest: String,
}, {
  timestamps: true,
});

// virtuals and other things here . . .

module.exports = User;
```

The CartProduct model looks like:

```js
'use strict';

const mongoose = require('mongoose');

const cartProductSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  size: {
    type: String,
    required: true,
  },
  image_url : {
    type: String,
    required: true,
  },
  quantity: {
    type: Number,
    required: true,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});

// cartProductSchema.virtual('length').get(function length() {
//   return this.text.length;
// });

const CartProduct = mongoose.model('CartProduct', cartProductSchema);

module.exports = CartProduct;
```

The error I am getting is as follows:

```
/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/node_modules/mongoose/lib/schema.js:640
        throw new TypeError('Undefined type `' + name + '` at array `' + path +
        ^

TypeError: Undefined type `model` at array `cart`
    at Function.Schema.interpretAsType (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/node_modules/mongoose/lib/schema.js:640:15)
    at Schema.path (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/node_modules/mongoose/lib/schema.js:547:29)
    at Schema.add (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/node_modules/mongoose/lib/schema.js:429:12)
    at new Schema (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/node_modules/mongoose/lib/schema.js:100:10)
    at Object.<anonymous> (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/app/models/user.js:8:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/lib/wiring/loader.js:13:39
    at Array.forEach (native)
    at fs.readdirSync.filter.entry.forEach (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/lib/wiring/loader.js:12:5)
    at Object.<anonymous> (/Users/versigtig/Projects/GA-WDI/projects/tre-cool-beans/nozama/back-end/app/models/index.js:5:18)
    at Module._compile (module.js:409:26)
```

I have tried simply defining the `cartProductSchema` at the top of `user.js` in the `User` model (being sure to include the `const CartProduct = mongoose.model('CartProduct', cartProductSchema);` line) and I still get the same error.

I feel like I am running into some issue with the way that our Express server has been wired up and I can't figure it out.

So: How do I make it so that `User` has a key of `cart` that is an array of embedded `CartProduct` documents?

**Comment by gaand** [comment]
That documentation is well out of date.

Maybe this will help: http://mongoosejs.com/docs/subdocs.html

**Comment by gaand** [comment]
Also, why the line removed below?

```diff
   cart: {
     type: [CartProduct], //Here we define that cart is an array of CartProduct
-    default: [],
   },
```

**Comment by joaufi** [comment]
Thank you for sending the updating documentation, did not even realize I was referencing old docs. By the new documentation I am still implementing it in the same way.

Hmm, I didn't remove that line? I left it as it is. Not sure where you're seeing that. 

I just tried removing the `default: []` line below just for kicks and it did not help my error. The model is still 'undefined'.

**Comment by joaufi** [comment]
Actually, as per the new documentation:

```js
var parentSchema = new Schema({
  children: [childSchema]
})
```

It looks like I have to make an array of the SCHEMA and not the Model. I am going to try that.

I think that is the problem. I am going to keep this issue open until I am sure it is working.

**Comment by joaufi** [comment]
Okay, it looks like that is the correct implementation. So, to make an embedded document I now have `users.js` looking like this:

```js
'use strict';

const bcrypt = require('bcrypt');
const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator');

const cartProductSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  size: {
    type: String,
    required: true,
  },
  image_url : {
    type: String,
    required: true,
  },
  quantity: {
    type: Number,
    required: true,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});

const userSchema = new mongoose.Schema({
  email: {
    type: String,
    unique: true,
    required: true,
  },
  cart: {
    type: [cartProductSchema],
    default: [],
  },
  token: {
    type: String,
    require: true,
  },
  passwordDigest: String,
}, {
  timestamps: true,
});

// rest of the file, virtuals/exports etc . . .

```

I have tested it by trying to add a CartProduct document and it does add it correctly. I have not tried exporting CartProduct as a model but so far I don't see a need as registering it as a Model with mongoose/mongodb.

Closing this issue for now, if I do happen to run into more problems with needing CartProduct as a registered model I will reopen.

**Comment by gaand** [comment]
I strongly suggest you refactor that to have the CartProduct model exported from a separate file as you did and grab the schema from the model, or have  the schema exported from a separate file.

**Comment by joaufi** [comment]
Just looked up how to do that, thanks for the recommendation! Will implement that now.

**Comment by joaufi** [comment]
So anyone else who might be having this problem knows what I did:

cartproduct.js looks like this:

```js
'use strict';

const mongoose = require('mongoose');

const cartProductSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  size: {
    type: String,
    required: true,
  },
  image_url : {
    type: String,
    required: true,
  },
  quantity: {
    type: Number,
    required: true,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});

// cartProductSchema.virtual('length').get(function length() {
//   return this.text.length;
// });

const CartProduct = mongoose.model('CartProduct', cartProductSchema);

module.exports = CartProduct;
```

and user.js looks like:

```js
'use strict';

const bcrypt = require('bcrypt');
const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator');

const cartProductSchema = mongoose.model('CartProduct').schema;

const userSchema = new mongoose.Schema({
  email: {
    type: String,
    unique: true,
    required: true,
  },
  cart: {
    type: [cartProductSchema],
    default: [],
  },
  token: {
    type: String,
    require: true,
  },
  passwordDigest: String,
}, {
  timestamps: true,
});

// virtuals, rest of file, etc . . .

```

Thanks again @gaand !
