### ISSUE TITLE
git problem

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/group-project#251]
My directory for the team project api is connected to my profile Soboscott/squad-complex-project-api.

In my profile / repositories there is no repo forked with that name.  I would like some advice before doing anything destructive with the repo, or the directory.

Thanks for helping.

**Comment by bernardlee** [comment]
Run `git remote -v` to view all of your remotes.  Remove the ones that you don't want with `git remote remove <name>` and add the group's repository with `git remote add <name> <ssh>`.

**Comment by BenGitsCode** [comment]
☝️ Think of the remote as where you're pointing your push/pulls.  

Let us know where you are after using Bernards suggestion.

**Comment by Soboscott** [comment]
It wouldn't let me remove the directory:
Last night I tried to remove it from the finder and this morning
I tried pulling from the development branch and got the following:
```

git remote -v
origin	git@github.com:SquadComplex/squad-complex-project-api.git (fetch)
origin	git@github.com:SquadComplex/squad-complex-project-api.git (push)
~/wdi/projects/squad-complex-project-api (blog-crud)
$ git remote remove SquadComplex/squad-complex-project-api.git
fatal: No such remote: SquadComplex/squad-complex-project-api.git
~/wdi/projects/squad-complex-project-api (blog-crud)
$ git remote remove SquadComplex/squad-complex-project-api
fatal: No such remote: SquadComplex/squad-complex-project-api
~/wdi/projects/squad-complex-project-api (blog-crud)
$ git branch
* blog-crud
  development
  master
~/wdi/projects/squad-complex-project-api (blog-crud)
$ git checkout deveopment
error: pathspec 'deveopment' did not match any file(s) known to git.
~/wdi/projects/squad-complex-project-api (blog-crud)
$ gti checkout development
-bash: gti: command not found
~/wdi/projects/squad-complex-project-api (blog-crud)
$ git checkout development
Switched to branch 'development'
Your branch is behind 'origin/development' by 5 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
~/wdi/projects/squad-complex-project-api (development)
$ git pull origin development
From github.com:SquadComplex/squad-complex-project-api
 * branch            development -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Fast-forwarded development to 8c56f0a505ce59b935fd5d6e92aa7e802c9b0f6e.
~/wdi/projects/squad-complex-project-api (development)
$

**Comment by raq929** [comment]
It looks like you successfully pulled from development. What's the problem right now?

**Comment by Soboscott** [comment]
I wasn't sure if I needed to do anything with this:
First, rewinding head to replay your work on top of it...
Fast-forwarded development to 8c56f0a505ce59b935fd5d6e92aa7e802c9b0f6e.
but now I see that this was just showing what was done, not what I needed to do.
thank you.

**Comment by Soboscott** [comment]
This is the error I am getting back from nodemon:

```
$ cd squad-complex-project-api/
~/wdi/projects/squad-complex-project-api (development)
$ nodemon
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./bin/express server`
module.js:471
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/scottlandry/wdi/projects/squad-complex-project-api/server.js:2:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[nodemon] app crashed - waiting for file changes before starting...
^C~/wdi/projects/squad-complex-project-api (development)

```

**Comment by raq929** [comment]
You have not run `npm install`

**Comment by Soboscott** [comment]
you Rock!!!
Thank You!!
