### ISSUE TITLE
Local server crashing due to error from node_modules

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/group-project#318]
My localhost keeps crashing, with the base of the error stack located at the following location

```shell
ReferenceError: handleError is not defined
    at /Users/Alex/wdi/projects/groupProject/surveyPlatformAPI/app/controllers/questions.js:56:25
    at /Users/Alex/wdi/projects/groupProject/surveyPlatformAPI/node_modules/mongoose/lib/model.js:3745:16
    at /Users/Alex/wdi/projects/groupProject/surveyPlatformAPI/node_modules/mongoose/lib/services/model/applyHooks.js:153:17
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Because this is in the node modules, I am hesitant to touch it and do not really understand either what it is or why it is failing. Any help would be appreciated.

UPDATE: my server actually is not inherently broken, it just breaks when I run this curl script (meant to update questions), throwing me an error reading `curl: (52) Empty reply from server

```curl
API="http://localhost:4741"
URL_PATH="/questions"
ID="59244f50810a4f24084a2543"

curl "${API}${URL_PATH}/${ID}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --data '{
    "question": {
      "results": [{
        "response": true
      }]
    }
  }'

echo
```
Why would my curl script fubar my server?

**Comment by scottyscripts** [comment]
Can you paste your exact error message? When are you getting this error?

**Comment by d00medman** [comment]
just updated initial message w/more info

**Comment by scottyscripts** [comment]
can you post your controller code for update? Have you tried logging within that function to get a better idea of when you actually hit that error?

**Comment by d00medman** [comment]
```js
'use strict'

const controller = require('lib/wiring/controller')
const models = require('app/models')
const Question = models.question

const authenticate = require('./concerns/authenticate')
const setUser = require('./concerns/set-current-user')
const setModel = require('./concerns/set-mongoose-model')

// index and show is going to be largely the same as they are in
// survey. Show will be indiscriminate while index will be linked
// to the ID of its owner
const index = (req, res, next) => {
  Question.find()
    .then(question => res.json({
      question: question.map((e) =>
        e.toJSON({ virtuals: true})), // no
    }))
    .catch(next);
}

const show = (req, res) => {
  res.json({
    question: req.question.toJSON({ virtuals: true}),
  })
}

// create is going to need to be called in congress with create survey so
// that survey can pass its ID to the questions
const create = (req, res, next) => {
  let question = Object.assign(req.body.question, {
    _survey: req.body.question._survey
    // this pretty much mandates that question be created in concert with
    // survey
  });
  Question.create(question)
    .then(question =>
      res.status(201)
        .json({
          question: question.toJSON({ virtuals: true, user: req.user }),
        }))
    .catch(next)
}

// basically using standard issue long form update here. Not sure if it will work or If I will need something more elaborate. Also need to plan for the strong probability that it is simply not possible to touch the array without some form of authentication.
const update = (req, res, next) => {
  Question.findById(req.params.id, function(err, question) {
    if (err) {
      res.status(422).send(err);
    } else {
      // I am actually unsure of exactly what will be pushed to the results array. Using req.params.data as a standin until I hit this problem head on.
          question.results = question.results.push(req.params.data)
    }
    question.save(function (err, updatedQuestion) {
        if (err) return handleError(err);
        res.send(updatedQuestion);
      });
  })
}

// allows for deletion of single question
const destroy = (req, res, next) => {
  req.question.remove()
    .then(() => res.sendStatus(204))
    .catch(next)
}

module.exports = controller({
  index,
  show,
  create,
  update,
  destroy,
}, { before: [
  { method: setUser, only: ['index', 'show'] },
  { method: authenticate, except: ['index', 'show', 'update'] },
  { method: setModel(Question), only: ['show'] },
  { method: setModel(Question, { forUser: true }), only: ['update', 'destroy'] },
], })
```

I'm not sure I follow re: console logging within the function. Isn't curl a way to just perform the HTTP request on the back end, bypassing the need for a function? As things stand, my update function is actually closer to pseudocode than anything else. Do I need to articulate the logic in order to move forward with the CURL request?

**Comment by scottyscripts** [comment]
I was referring to logging the function server side. When you use curl, you are still making an HTTP request. how that request is handled is 100% determined by the logic in your API. Put some console.logs in your update function on your server to get a better idea of what is happening. You don't need $.ajax client side code to work in order to make a curl request, but your API logic should be sound.

**Comment by d00medman** [comment]
This was actually extremely useful to learn. With the ability to look into my update method (something which I had been previously unable to do), I was actually able to hash out the logic of the update method. My update method is written as follows:

```js
const update = (req, res, next) => {
  Question.findById(req.params.id, function(err, question) {
    if (err) {
      res.status(422).send(err)
    } else {
      question.results.push(req.body.question.results)
    }

    question.save(function (err, updatedQuestion) {
      console.log(JSON.stringify(updatedQuestion))
      if (err) {
        res.status(500).send(err)
      }
        res.send(updatedQuestion)
      })
  })
}
```

The first part of this works, but the question.save block throws the following 500 error:

```shell
{"errors":{"results.0._id":{"message":"Cast to ObjectID failed for value \"[ { response: true } ]\" at path \"_id\"","name":"CastError","stringValue":"\"[ { response: true } ]\"","kind":"ObjectID","value":[{"response":true}],"path":"_id","reason":{"message":"Cast to ObjectId failed for value \"[ { response: true } ]\" at path \"_id\"","name":"CastError","stringValue":"\"[ { response: true } ]\"","kind":"ObjectId","value":[{"response":true}],"path":"_id"}}},"_message":"Question validation failed","name":"ValidationError"}
```

500 errors have been my absolute bane in the past, as they block my console logs from outputting to the console, making debugging an absolute pain.

UPDATE: Turns out my code is actually faking the 500 error and I can write to the server. The problem appears to be that nothing is being passed to updatedQuestion. 

UPDATE 2: This is actually pretty mystifying, as I basically copied this save functionality from the documentation. Why is updatedQuestion failing to link to anything?

**Comment by d00medman** [comment]
Turns out that the problem could be solved by switching my update methodology to using the inbuilt mongoose update method. 

Final controller code:
```js
const update = (req, res, next) => {
  Question.findByIdAndUpdate(req.params.id, { $push: { results: req.body.question.results }}, function (err, question) {
    if (err) return handleError(err)
    res.send(question)
  })
```
