### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by Fcarrion001** [ga-wdi-boston/group-project#383]
I cannot figure out how to update the blog parent document with the post child document
I am sending a 204 response header then I believe a 500 error is happening afterwards resulting in the error I am receiving. 

```javascript
const create = (req, res, next) => {
  const findBlogId = req._parsedUrl.pathname.split('/')
  const blogId = findBlogId[2]
  const post = Object.assign(req.body.posts, {
    _owner: blogId
  })
  const blogToUpdate = req.params.id === findBlogId[2]
  console.log('this is post', post)
  return Blog.findOneAndUpdate(blogToUpdate)
    // .then(data => console.log('this is data ', data))
    .then(data => data.posts.push(post))
      .then((post) => post.save)
      .then((post) => res.sendStatus(204)
        .json({
          posts: post.toJSON({ virtuals: true, post: req.body.posts })
        }))
    .catch(next)
}

**This is the full error I am receiving** 

(node:58661) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
Server listening on port 4741
this is post { title: 'POST1',
  body: 'DSKJFLFJDSLKFJDLSKFJDLKJS',
  _owner: '5989bdac1e09c5de6ff8a525' }
POST /blogs/5989bdac1e09c5de6ff8a525/posts 500 54.088 ms - -
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/response.js:730:10)
    at ServerResponse.json (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/response.js:253:10)
    at errorHandler (/Users/franklincarrion/WDI/projects/Project-3-backend/app/middleware/error-handler.js:19:33)
    at Layer.handle_error (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:315:13)
    at /Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:315:13)
    at /Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/franklincarrion/WDI/projects/Project-3-backend/node_modules/express/lib/router/index.js:315:13)

**Comment by payne-chris-r** [comment]
first, line up your `.then()`s. Then see if you're sending multiple responses from a single controller action.

**Comment by cpearce31** [comment]
Any progress here?

**Comment by Fcarrion001** [comment]
Apologies the issue has been resolved. I was sending the response then attempting to write it. Changing .sendStatus(204) to .status(204) corrected the problem
