### ISSUE TITLE
npm install - multiple errors

### ISSUE THREAD

**Issue by ndotlara** [ga-wdi-boston/group-project#398]
Running npm install to set up the back end (from the Express API template) and I'm getting several errors (too many to copy).  Would someone please meet with me to look at them? 

Thank you!

**Comment by ndotlara** [comment]
bash terminal errors:

`$ npm install
```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning CERT_HAS_EXPIRED: request to https://registry.npmjs.org/bcrypt failed, reason: certificate has expired
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> bcrypt@1.0.3 install /Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@6.11.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: certificate has expired
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/natalialara/.nvm/versions/node/v6.11.1/bin/node" "/Users/natalialara/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/natalialara/.nvm/versions/node/v6.11.1/bin/node /Users/natalialara/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/natalialara/.nvm/versions/node/v6.11.1/bin/node" "/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt
node-pre-gyp ERR! node -v v6.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/Users/natalialara/.nvm/versions/node/v6.11.1/bin/node /Users/natalialara/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/natalialara/wdi/projects/team-project-master/survey-kit-back/node_modules/bcrypt/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/natalialara/.npm/_logs/2017-09-13T18_37_55_859Z-debug.log
```
~/wdi/projects/team-project-master/survey-kit-back (development)`

**Comment by ndotlara** [comment]
not sure how, but Coptia fixed it! Closing issue.
