### ISSUE TITLE
aws delete object

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/group-project#85]
i'm trying to delete an object from my bucket but i keep getting an 'access denied' message... when was access ever granted? how do i authorize myself?

**Comment by apalmer0** [comment]
here's my controller:

```
const destroy = (req, res, next) => {
  let path = 'https://apalmer0.s3.amazonaws.com/';
  let fileLocation = req.headers.imagelocation;
  let fileName = fileLocation.replace(path, '');

  let s3 = new AWS.S3();
  let params = {  Bucket: 'apalmer0', Key: fileName };

  new Promise((resolve, reject) =>
    s3.deleteObject(params, (err, data) =>
      err ? reject(err) : resolve(data)
    )
  ).then((awsS3Response) =>
    console.log(awsS3Response)
  ).catch(err => next(err));
};
```

**Comment by jrhorn424** [comment]
AWS permissions can't be ruled out yet, but they appeared to be set correctly and there were a few issues to clean up with the client and server code.

On the client:

1. Clean up export, import, and access of global data.
1. Remove jQuery AJAX formdata options.
1. Remove data from DELETE request.
1. Remove unneeded headers.

On the server:

1. Use mongo to get an S3 bucket location instead of passing it through headers.
1. Clean-up mongo record on successful S3 deletion.

Still to do:

1. Verify token is correct when deleting.
1. Verify a delete can happen outside the web server.

**Comment by apalmer0** [comment]
On the client:

**1. ~~Clean up export, import, and access of global data.~~**
**1. ~~Remove jQuery AJAX formdata options.~~**
**1. ~~Remove data from DELETE request.~~**
**1. ~~Remove unneeded headers.~~**

On the server:

**1. ~~Use mongo to get an S3 bucket location instead of passing it through headers.~~**
1. Clean-up mongo record on successful S3 deletion.

delete request returns response below

Still to do:

**1. ~~Verify token is correct when deleting.~~**
1. Verify a delete can happen outside the web server.

Not sure how to verify this - I can delete from AWS but don't know how to do it from the terminal.



```
DELETE /images/56e7215f49fd83bd822a4c25 - - ms - -
{ [AccessDenied: Access Denied]
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: Mon Mar 14 2016 17:20:35 GMT-0400 (EDT),
  requestId: '47E56B5DA7BD17C4',
  extendedRequestId: 'dm2KuQPyW+rc76UeQiJHDAJrhHqtmngbtOSA4s6Da7BETIC5YLcz/li9SqahNYfJnpUTBjZ0g6Y=',
  statusCode: 403,
  retryable: false,
  retryDelay: 46.13028927706182 } 'AccessDenied: Access Denied\n    at Request.extractError (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/services/s3.js:327:35)\n    at Request.callListeners (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:596:14)\n    at Request.transition (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:21:10)\n    at AcceptorStateMachine.runTo (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:37:9)\n    at Request.<anonymous> (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:598:12)\n    at Request.callListeners (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\n    at Request.emit (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:596:14)\n    at Request.transition (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:21:10)\n    at AcceptorStateMachine.runTo (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/andrewpalmer/wdi/training/express-multer-api/node_modules/aws-sdk/lib/request.js:37:9)'

```

**Comment by gaand** [comment]
The policy generated in the [setup guide](/ga-wdi-boston/aws-s3-setup-guide), only permits

```json
"Action": [
  "s3:PutObjectAcl",
  "s3:PutObject"
],
```

so I think permissions.  The [policy generator](http://awspolicygen.s3.amazonaws.com/policygen.html) includes dozens of other `Action`s including `DeleteObject`.

**Comment by jrhorn424** [comment]
@apalmer0 Let me know the status after you've adjusted permissions.

**Comment by J-Weeks** [comment]
@jrhorn424 tabled this to work on other features for now.
